require('just-the-job') ->
	@task 'update',
		'Get latest versions of modules',
		'npm update'
	@task 'clean',
		'Get rid of things generated by building',
		'rm -rf node_modules compiler-js js'
	@job 'lint-coffee',
		'coffeelint --file source/coffeelint-config.json source'
	@job 'lint-JS',
		'jshint source'
	@task 'lint',
		'Check code formatting of coffeescript and javascript',
		['lint-coffee', 'lint-JS']
	@task 'compile-compiler',
		'Compile the Smith-Compiler to compiler-js',
		'coffee --compile --bare --map --output compiler-js source/Smith-Compiler'
	@task 'compile',
		'Compile all code in source',
		['compile-compiler'],
		'bin/smith --quiet' #  --print-module-defines
	@task 'run',
		'Run the compiled program',
		['compile'],
		'node js/run.js'
	@task 'watch',
		'Compile all modifications to source',
		'bin/smith --in source --out js-smith --watch'

	@task 'all', 'Do everything!', ['clean', 'update', 'lint', 'run']
