#!/usr/bin/sh
echo COMPILE
script/compile

echo LINT
coffeelint -f script/lintConfig.json src/*.coffee

echo DOC
cd src
coffeedoc *.coffee --output ../about/coffeeDocs
cd ..


echo
echo TEST
script/test

echo
echo RUN
script/run
